apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: efguskfcz-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-720c78dbf7.hw8l.p3.openshiftapps.com/rhtap/rhtap-qe-go:81af4b192e842b15505892e0737a10730d5414ed@sha256:0d9a359b12d11f5c241ba9ada56544d9b6d6c79e28606b0d0061d9b85f345bdc
          name: container-image
